# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from IconSource import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1486, 906)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Real_Road_FC_tab = QtWidgets.QWidget()
        self.Real_Road_FC_tab.setObjectName("Real_Road_FC_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Real_Road_FC_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1371, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_5.addWidget(self.plainTextEdit_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_3.setSizePolicy(sizePolicy)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_5.addWidget(self.plainTextEdit_3)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_4.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_4.setSizePolicy(sizePolicy)
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.verticalLayout_5.addWidget(self.plainTextEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 0, 10, -1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_DBC = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_DBC.sizePolicy().hasHeightForWidth())
        self.open_DBC.setSizePolicy(sizePolicy)
        self.open_DBC.setMinimumSize(QtCore.QSize(40, 25))
        self.open_DBC.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.open_DBC.setText("")
        self.open_DBC.setObjectName("open_DBC")
        self.verticalLayout_2.addWidget(self.open_DBC)
        self.open_CAR = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_CAR.sizePolicy().hasHeightForWidth())
        self.open_CAR.setSizePolicy(sizePolicy)
        self.open_CAR.setMinimumSize(QtCore.QSize(40, 25))
        self.open_CAR.setMaximumSize(QtCore.QSize(90, 25))
        self.open_CAR.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"\n"
"")
        self.open_CAR.setText("")
        self.open_CAR.setObjectName("open_CAR")
        self.verticalLayout_2.addWidget(self.open_CAR)
        self.open_DRIVER = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_DRIVER.sizePolicy().hasHeightForWidth())
        self.open_DRIVER.setSizePolicy(sizePolicy)
        self.open_DRIVER.setMinimumSize(QtCore.QSize(40, 25))
        self.open_DRIVER.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.open_DRIVER.setText("")
        self.open_DRIVER.setObjectName("open_DRIVER")
        self.verticalLayout_2.addWidget(self.open_DRIVER)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setStyleSheet("QPushButton{border-image: url(./Image/Set_name.png);}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView.setMaximumSize(QtCore.QSize(100000, 10000))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_1.addLayout(self.horizontalLayout)
        self.DatatableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.DatatableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.DatatableView.setObjectName("DatatableView")
        self.verticalLayout_1.addWidget(self.DatatableView)
        self.tabWidget.addTab(self.Real_Road_FC_tab, "")
        self.System_Gain_tab = QtWidgets.QWidget()
        self.System_Gain_tab.setObjectName("System_Gain_tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.System_Gain_tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 1401, 771))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 40, 1021, 721))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 20, 821, 421))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(30, 450, 261, 251))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(310, 450, 261, 251))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_7.setGeometry(QtCore.QRect(590, 450, 261, 251))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.Input_SysGain_data = QtWidgets.QPushButton(self.tab)
        self.Input_SysGain_data.setGeometry(QtCore.QRect(710, 10, 41, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_SysGain_data.sizePolicy().hasHeightForWidth())
        self.Input_SysGain_data.setSizePolicy(sizePolicy)
        self.Input_SysGain_data.setMinimumSize(QtCore.QSize(40, 25))
        self.Input_SysGain_data.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.Input_SysGain_data.setText("")
        self.Input_SysGain_data.setObjectName("Input_SysGain_data")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 100, 20))
        self.label_7.setMinimumSize(QtCore.QSize(100, 20))
        self.label_7.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(100, 10, 600, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_5.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_5.setSizePolicy(sizePolicy)
        self.plainTextEdit_5.setMinimumSize(QtCore.QSize(600, 10))
        self.plainTextEdit_5.setMaximumSize(QtCore.QSize(600, 30))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.Add_to_compare = QtWidgets.QPushButton(self.tab)
        self.Add_to_compare.setGeometry(QtCore.QRect(1280, 700, 41, 41))
        self.Add_to_compare.setStyleSheet("QPushButton{border-image: url(./Image/PlusIcon.png);}")
        self.Add_to_compare.setText("")
        self.Add_to_compare.setObjectName("Add_to_compare")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(1220, 710, 100, 20))
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(29, 40, 281, 721))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 241, 466))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 30))
        self.label_5.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 20))
        self.label_6.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.comboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.verticalLayout.addWidget(self.comboBox_1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(100, 20))
        self.label_10.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(100, 20))
        self.label_11.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(100, 20))
        self.label_12.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(100, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(100, 20))
        self.label_14.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout.addWidget(self.comboBox_6)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(100, 20))
        self.label_15.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout.addWidget(self.comboBox_7)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(100, 20))
        self.label_16.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.verticalLayout.addWidget(self.comboBox_8)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(20, 560, 100, 20))
        self.label_19.setMinimumSize(QtCore.QSize(100, 20))
        self.label_19.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 530, 100, 20))
        self.label_18.setMinimumSize(QtCore.QSize(100, 20))
        self.label_18.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 560, 171, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(90, 530, 171, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 490, 237, 30))
        self.label_20.setMinimumSize(QtCore.QSize(100, 30))
        self.label_20.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setObjectName("label_20")
        self.SysGain_cal = QtWidgets.QPushButton(self.groupBox)
        self.SysGain_cal.setGeometry(QtCore.QRect(40, 600, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.SysGain_cal.setFont(font)
        self.SysGain_cal.setStyleSheet("QPushButton{border-image: url(./Image/RunIcon.png);}\n"
"")
        self.SysGain_cal.setObjectName("SysGain_cal")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 50, 281, 681))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 241, 520))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setMinimumSize(QtCore.QSize(100, 30))
        self.label_30.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_31.setMinimumSize(QtCore.QSize(100, 20))
        self.label_31.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.comboBox_17 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_17.setFont(font)
        self.comboBox_17.setObjectName("comboBox_17")
        self.verticalLayout_7.addWidget(self.comboBox_17)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_32.setMinimumSize(QtCore.QSize(100, 20))
        self.label_32.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.comboBox_18 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_18.setFont(font)
        self.comboBox_18.setObjectName("comboBox_18")
        self.verticalLayout_7.addWidget(self.comboBox_18)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_33.setMinimumSize(QtCore.QSize(100, 20))
        self.label_33.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_7.addWidget(self.label_33)
        self.comboBox_19 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setObjectName("comboBox_19")
        self.verticalLayout_7.addWidget(self.comboBox_19)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_34.setMinimumSize(QtCore.QSize(100, 20))
        self.label_34.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_7.addWidget(self.label_34)
        self.comboBox_20 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_20.setFont(font)
        self.comboBox_20.setObjectName("comboBox_20")
        self.verticalLayout_7.addWidget(self.comboBox_20)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_35.setMinimumSize(QtCore.QSize(100, 20))
        self.label_35.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_7.addWidget(self.label_35)
        self.comboBox_21 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_21.setFont(font)
        self.comboBox_21.setObjectName("comboBox_21")
        self.verticalLayout_7.addWidget(self.comboBox_21)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_36.setMinimumSize(QtCore.QSize(100, 20))
        self.label_36.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        self.comboBox_22 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_22.setFont(font)
        self.comboBox_22.setObjectName("comboBox_22")
        self.verticalLayout_7.addWidget(self.comboBox_22)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setMinimumSize(QtCore.QSize(100, 20))
        self.label_37.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.comboBox_23 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_23.setFont(font)
        self.comboBox_23.setObjectName("comboBox_23")
        self.verticalLayout_7.addWidget(self.comboBox_23)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_38.setMinimumSize(QtCore.QSize(100, 20))
        self.label_38.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_7.addWidget(self.label_38)
        self.comboBox_24 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_24.setFont(font)
        self.comboBox_24.setObjectName("comboBox_24")
        self.verticalLayout_7.addWidget(self.comboBox_24)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_43.setMinimumSize(QtCore.QSize(100, 20))
        self.label_43.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_7.addWidget(self.label_43)
        self.comboBox_25 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_25.setFont(font)
        self.comboBox_25.setObjectName("comboBox_25")
        self.verticalLayout_7.addWidget(self.comboBox_25)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setGeometry(QtCore.QRect(20, 620, 100, 20))
        self.label_39.setMinimumSize(QtCore.QSize(100, 20))
        self.label_39.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setGeometry(QtCore.QRect(20, 590, 100, 20))
        self.label_40.setMinimumSize(QtCore.QSize(100, 20))
        self.label_40.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_3.setGeometry(QtCore.QRect(90, 620, 171, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_4.setGeometry(QtCore.QRect(90, 590, 171, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        self.label_41.setGeometry(QtCore.QRect(20, 550, 237, 30))
        self.label_41.setMinimumSize(QtCore.QSize(100, 30))
        self.label_41.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setObjectName("label_41")
        self.Input_Test_data_4 = QtWidgets.QPushButton(self.tab_2)
        self.Input_Test_data_4.setGeometry(QtCore.QRect(510, 10, 41, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Test_data_4.sizePolicy().hasHeightForWidth())
        self.Input_Test_data_4.setSizePolicy(sizePolicy)
        self.Input_Test_data_4.setMinimumSize(QtCore.QSize(40, 25))
        self.Input_Test_data_4.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.Input_Test_data_4.setText("")
        self.Input_Test_data_4.setObjectName("Input_Test_data_4")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(100, 10, 400, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_8.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_8.setSizePolicy(sizePolicy)
        self.plainTextEdit_8.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setGeometry(QtCore.QRect(10, 10, 100, 20))
        self.label_42.setMinimumSize(QtCore.QSize(100, 20))
        self.label_42.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.System_Gain_tab, "")
        self.Compare_Results_tab = QtWidgets.QWidget()
        self.Compare_Results_tab.setObjectName("Compare_Results_tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Compare_Results_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 901, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 523, 120))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(130, 20))
        self.label_9.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_6.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_6.setSizePolicy(sizePolicy)
        self.plainTextEdit_6.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_6)
        self.Input_Test_data_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Test_data_2.sizePolicy().hasHeightForWidth())
        self.Input_Test_data_2.setSizePolicy(sizePolicy)
        self.Input_Test_data_2.setMinimumSize(QtCore.QSize(40, 25))
        self.Input_Test_data_2.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.Input_Test_data_2.setText("")
        self.Input_Test_data_2.setObjectName("Input_Test_data_2")
        self.horizontalLayout_2.addWidget(self.Input_Test_data_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setMinimumSize(QtCore.QSize(130, 20))
        self.label_17.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_7.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_7.setSizePolicy(sizePolicy)
        self.plainTextEdit_7.setMaximumSize(QtCore.QSize(400, 30))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_7)
        self.Input_Test_data_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Test_data_3.sizePolicy().hasHeightForWidth())
        self.Input_Test_data_3.setSizePolicy(sizePolicy)
        self.Input_Test_data_3.setMinimumSize(QtCore.QSize(40, 25))
        self.Input_Test_data_3.setStyleSheet("QPushButton{border-image: url(./Image/file.png);}\n"
"")
        self.Input_Test_data_3.setText("")
        self.Input_Test_data_3.setObjectName("Input_Test_data_3")
        self.horizontalLayout_3.addWidget(self.Input_Test_data_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("QPushButton{border-image: url(./Image/PlusIcon_2.png);}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.SysGain_cal_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.SysGain_cal_2.setGeometry(QtCore.QRect(580, 20, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        self.SysGain_cal_2.setFont(font)
        self.SysGain_cal_2.setStyleSheet("QPushButton{border-image: url(./Image/RunIcon.png);}\n"
"")
        self.SysGain_cal_2.setObjectName("SysGain_cal_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Compare_Results_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 210, 1151, 451))
        self.groupBox_4.setObjectName("groupBox_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_5.setGeometry(QtCore.QRect(20, 30, 361, 321))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_6.setGeometry(QtCore.QRect(400, 30, 361, 321))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_8.setGeometry(QtCore.QRect(780, 30, 361, 321))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.tabWidget.addTab(self.Compare_Results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1486, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontest2 = QtWidgets.QAction(MainWindow)
        self.actiontest2.setObjectName("actiontest2")
        self.menu_Engine_Working_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Engine_Working_Dist.setObjectName("menu_Engine_Working_Dist")
        self.menu_InputData = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.menu_InputData.setFont(font)
        self.menu_InputData.setObjectName("menu_InputData")
        self.menu_CalData = QtWidgets.QAction(MainWindow)
        self.menu_CalData.setObjectName("menu_CalData")
        self.menu_Exit = QtWidgets.QAction(MainWindow)
        self.menu_Exit.setObjectName("menu_Exit")
        self.menu_Guildlines = QtWidgets.QAction(MainWindow)
        self.menu_Guildlines.setObjectName("menu_Guildlines")
        self.menu_ContactUs = QtWidgets.QAction(MainWindow)
        self.menu_ContactUs.setObjectName("menu_ContactUs")
        self.menu_Shifting_Strategy = QtWidgets.QAction(MainWindow)
        self.menu_Shifting_Strategy.setObjectName("menu_Shifting_Strategy")
        self.menu_Speed_Dist = QtWidgets.QAction(MainWindow)
        self.menu_Speed_Dist.setObjectName("menu_Speed_Dist")
        self.actionSystemGain = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Image/EnergyIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSystemGain.setIcon(icon)
        self.actionSystemGain.setObjectName("actionSystemGain")
        self.actionRide = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/Image/RideIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRide.setIcon(icon1)
        self.actionRide.setObjectName("actionRide")
        self.actiontest_menu = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/Image/Set_name.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontest_menu.setIcon(icon2)
        self.actiontest_menu.setObjectName("actiontest_menu")
        self.menu.addAction(self.menu_InputData)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_Exit)
        self.menu_3.addAction(self.menu_Engine_Working_Dist)
        self.menu_3.addAction(self.menu_Shifting_Strategy)
        self.menu_3.addAction(self.menu_Speed_Dist)
        self.menu_2.addAction(self.menu_CalData)
        self.menu_4.addAction(self.menu_Guildlines)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_ContactUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionSystemGain)
        self.toolBar.addAction(self.actionRide)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.DatatableView, self.open_CAR)
        MainWindow.setTabOrder(self.open_CAR, self.open_DRIVER)
        MainWindow.setTabOrder(self.open_DRIVER, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.plainTextEdit_2)
        MainWindow.setTabOrder(self.plainTextEdit_2, self.plainTextEdit_3)
        MainWindow.setTabOrder(self.plainTextEdit_3, self.plainTextEdit_4)
        MainWindow.setTabOrder(self.plainTextEdit_4, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.comboBox_1)
        MainWindow.setTabOrder(self.comboBox_1, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.comboBox_7)
        MainWindow.setTabOrder(self.comboBox_7, self.comboBox_8)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DBC Index"))
        self.label_2.setText(_translate("MainWindow", "CAR Index"))
        self.label_3.setText(_translate("MainWindow", "DRIVER Index"))
        self.label_4.setText(_translate("MainWindow", "Save Name"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "AS24_test_Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Real_Road_FC_tab), _translate("MainWindow", "Real Road FC"))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出图片"))
        self.label_7.setText(_translate("MainWindow", "测试数据导入："))
        self.label_8.setText(_translate("MainWindow", "加入对比"))
        self.groupBox.setTitle(_translate("MainWindow", "配置"))
        self.label_5.setText(_translate("MainWindow", "字段选择："))
        self.label_6.setText(_translate("MainWindow", "车速(km/h)"))
        self.label_10.setText(_translate("MainWindow", "油门(-)"))
        self.label_11.setText(_translate("MainWindow", "加速度(g)"))
        self.label_12.setText(_translate("MainWindow", "档位(-)"))
        self.label_13.setText(_translate("MainWindow", "时间(s)"))
        self.label_14.setText(_translate("MainWindow", "扭矩(N.m)"))
        self.label_15.setText(_translate("MainWindow", "油耗(ul/s)"))
        self.label_16.setText(_translate("MainWindow", "发动机转速(rpm)"))
        self.label_19.setText(_translate("MainWindow", "踏板信号："))
        self.label_18.setText(_translate("MainWindow", "稳态车速："))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入踏板信号，以空格为间隔</p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入稳态车速，以空格为间隔</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "附加输入："))
        self.SysGain_cal.setText(_translate("MainWindow", "    计  算"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "AT/DCT"))
        self.groupBox_5.setTitle(_translate("MainWindow", "配置"))
        self.label_30.setText(_translate("MainWindow", "字段选择："))
        self.label_31.setText(_translate("MainWindow", "车速(km/h)"))
        self.label_32.setText(_translate("MainWindow", "油门(-)"))
        self.label_33.setText(_translate("MainWindow", "加速度(g)"))
        self.label_34.setText(_translate("MainWindow", "档位(-)"))
        self.label_35.setText(_translate("MainWindow", "时间(s)"))
        self.label_36.setText(_translate("MainWindow", "扭矩(N.m)"))
        self.label_37.setText(_translate("MainWindow", "油耗(ul/s)"))
        self.label_38.setText(_translate("MainWindow", "发动机转速(rpm)"))
        self.label_43.setText(_translate("MainWindow", "涡轮转速(rpm)"))
        self.label_39.setText(_translate("MainWindow", "踏板信号："))
        self.label_40.setText(_translate("MainWindow", "稳态车速："))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入踏板信号，以空格为间隔</p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入稳态车速，以空格为间隔</p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "附加输入："))
        self.label_42.setText(_translate("MainWindow", "测试数据导入："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "CVT"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "MT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.System_Gain_tab), _translate("MainWindow", "System Gain"))
        self.groupBox_3.setTitle(_translate("MainWindow", "计算结果导入"))
        self.label_9.setText(_translate("MainWindow", "历史测试数据导入："))
        self.label_17.setText(_translate("MainWindow", "历史测试数据导入："))
        self.SysGain_cal_2.setText(_translate("MainWindow", "    对   比"))
        self.groupBox_4.setTitle(_translate("MainWindow", "对比图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Compare_Results_tab), _translate("MainWindow", "Compare Results"))
        self.menu.setTitle(_translate("MainWindow", "文件 (File)"))
        self.menu_3.setTitle(_translate("MainWindow", "绘图 (Ploting)"))
        self.menu_2.setTitle(_translate("MainWindow", "计算 (Calculation)"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助 (Help)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest2.setText(_translate("MainWindow", "test2"))
        self.menu_Engine_Working_Dist.setText(_translate("MainWindow", "发动机工况点分布 Engine Work Point Dist."))
        self.menu_InputData.setText(_translate("MainWindow", "导入测试数据 Input Test Data"))
        self.menu_CalData.setText(_translate("MainWindow", "求解 Solution"))
        self.menu_Exit.setText(_translate("MainWindow", "退出"))
        self.menu_Guildlines.setText(_translate("MainWindow", "操作指南 Guildlines"))
        self.menu_ContactUs.setText(_translate("MainWindow", "联系作者 Contact Us!"))
        self.menu_Shifting_Strategy.setText(_translate("MainWindow", "换挡策略分布 Shifting Strategy Dist."))
        self.menu_Speed_Dist.setText(_translate("MainWindow", "速度分布 Speed Dist."))
        self.actionSystemGain.setText(_translate("MainWindow", "SystemGain"))
        self.actionSystemGain.setToolTip(_translate("MainWindow", "SystemGain"))
        self.actionSystemGain.setShortcut(_translate("MainWindow", "F1"))
        self.actionRide.setText(_translate("MainWindow", "Ride"))
        self.actionRide.setToolTip(_translate("MainWindow", "Ride"))
        self.actionRide.setShortcut(_translate("MainWindow", "F2"))
        self.actiontest_menu.setText(_translate("MainWindow", "test_menu"))

